spring.application.name: spring-batch-bigdataflow-sample

spring:
  # Batch Application Meta Data Schema Setting
  batch.jdbc.initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:23306/default
    username: default
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

logging:
  level:
    root: info
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE
